name: study_phonics
description: study phonics easily.
publish_to: 'none'
version: 1.5.5+56

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter

  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  # Firebase Analytics
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  # Admob (Android only)
  google_mobile_ads: ^7.0.0
  app_tracking_transparency: ^2.0.6+1
  # Text to Speech
  flutter_tts: ^4.2.5
  #env
  flutter_dotenv: ^6.0.0
  #MVVM
  hooks_riverpod: ^3.2.1
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App Splash
  flutter_native_splash: ^2.4.7

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#03a9f4"
  adaptive_icon_foreground: "assets/icon/appIcon.png"

flutter_native_splash:
  image: "assets/icon/splash.png"
  color: "#03a9f4"
  android_12:
    image: "assets/icon/icon.png"
    icon_background_color: "#03a9f4"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/.env
  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf